.TH "RUNSYSSV" "1" "October 2020" "sysmgr-VERSION" "General Commands Manual"
.SH NAME
runsyssv \- run sysmgr services
.SH SYNOPSIS
runsyssv [service file]
.SH DESCRIPTION
runsyssv is the program that sysmgr uses in order to run, track, and properly
terminate services. It is normally meant to be used by sysmgr only, not by
users.
.SH AUTHOR
Cem Keylan <cem@ckyln.com>
.SH SEE ALSO
.BR
sysmgr(8)
svctl(1)
