.TH "SYSMGR-DEPENDS" "1" "October 2020" "sysmgr-VERSION" "General Commands Manual"
.SH NAME
sysmgr-depends \- dependency manager for sysmgr services
.SH SYNOPSIS
sysmgr-depends [service...]
.SH DESCRIPTION
sysmgr-depends is a simple tool that can be incorporated into sysmgr services
to wait until the given services are up.
.SH AUTHOR
Cem Keylan <cem@ckyln.com>
.SH SEE ALSO
.BR svctl(1)
.BR sysmgr(8)
